spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:./db/tree
    username:
    password:

  liquibase:
    changeLog: 'classpath:db/changelog.xml'


logging:
  level:
    ROOT: INFO
